A/home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path("post/delete/<int:post_id>/", views.PostDeleteView.as_view(), name='post_delete'),
    path("post/update/<int:post_id>/", views.PostUpdateView.as_view(), name='post_update'),
    path("post/create/", views.PostCreateView.as_view(), name='post_create'),
    path("reply/<int:post_id>/<int:comment_id>/", views.PostAddReplyView.as_view(), name='add_reply'),
    path("like/<int:post_id>/", views.PostLikeView.as_view(), name='post_like'),
]

A/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="postss")
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    #Meta options
    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("home:post_detail", args=(self.id, self.slug))

    def like_count(self):
        return self.pvote.count()

    def user_can_like(self, user):
        user_like = user.uvote.filter(post=self)
        if user_like.exists():
            return True
        return False
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="Ucomment")
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="Pcomment")
    reply = models.ForeignKey("self", on_delete=models.CASCADE, related_name="rcomments", blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="uvote")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pvote")

    def __str__(self):
        return f'{self.user} liked {self.post.slug}'

A/home/forms.py
from django import forms
from .models import Post, Comment
class PostCreateAndUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["body",]


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']


class PostSearchForm(forms.Form):
    Search = forms.CharField()

A/home/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views import View
from .models import Post, Comment, Vote
from django.contrib import messages
from .forms import PostCreateAndUpdateForm, CommentCreateForm, CommentReplyForm, PostSearchForm
from django.utils.text import slugify

class HomeView(View):
    form_class = PostSearchForm
    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get("Search"):
            posts = posts.filter(body__contains=request.GET["Search"])
        return render(request, "home/index.html", context={"posts":posts, "form":self.form_class})

class PostDetailView(View):
    form_class = CommentCreateForm
    form_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs["post_id"], slug=kwargs["post_slug"])
        return super().setup(request, *args, **kwargs)
    def get(self, request, post_id, post_slug):
        comment = self.post_instance.Pcomment.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        return  render(request, "home/detail.html", {"post":self.post_instance, "comments":comment, "form":self.form_class, "reply_form":self.form_reply, "can_like":can_like})
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_commit  = form.save(commit=False)
            new_commit.user = request.user
            new_commit.post = self.post_instance
            new_commit.save()
            return redirect("home:post_detail", self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    login_url = 'account:user_login'
    def get(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, "post is deleted successfully.", 'success')
        else:
            messages.error(request, "you cant deleted this post.", 'danger')
        return redirect("home:home")

class PostUpdateView(LoginRequiredMixin, View):
    login_url = 'account:user_login'
    form_class = PostCreateAndUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(id=kwargs["post_id"])
        return super().setup(request, *args, **kwargs)


    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not request.user.id == post.user.id:
            messages.error(request, "user not correct.", "danger")
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, "home/update.html", context={"form":form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, "you updated this post", 'success')
            return redirect("home:post_detail", post.id,post.slug)

class PostCreateView(LoginRequiredMixin, View):
    login_url = 'account:user_login'
    form_class = PostCreateAndUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, "home/create.html", context={"form":form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, "you create this post", 'success')
            return redirect("home:post_detail", new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    login_url = 'account:user_login'
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'your reply submitted successfully.', 'success')
        return redirect('home:post_detail', post.id, post.slug)

class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, 'you have already logind', 'danger')
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, 'you liked this post', 'success')
        return redirect('home:post_detail', post.id, post.slug)

A/home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

A/home/templates/home/detail.html
{% extends 'base.html'%}
{% block content %}

    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger"> Delete </a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-info"> Update </a>
    {% endif %}
    <a href="{% url 'account:user_profile' post.user.id %}"> {{post.user.username}}</a>
    <p>{{post.body}}</p><hr/>
    {% if request.user.is_authenticated %}
        <a href="{% url 'home:post_like' post.id %}" class="{% if can_like %}disabled{% endif %}  btn btn-primary col-md-2">like {{ post.like_count }}</a>


        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="send">
        </form><br/>
    {% else %}
        <p class="alert alert-danger">for leave a commnet you should be loggind.</p>
    {% endif %}
    {% for comment in comments%}
        <div class="card-body bg-dark text-white">
            <p class="header">{{comment.user}} | {{comment.created|timesince}}</p>
            <p class="card-body">{{comment.body}}</p>
            {% if request.user.is_authenticated %}
            <form action="{% url 'home:add_reply' post.id comment.id %}" method="post">
                {% csrf_token %}
                {{reply_form.as_p}}
                <input type="submit" value="send">
             </form><br/>
            {% endif %}


            {% with replies=comment.rcomments.all %}
            {% for reply in replies %}
                <p class="bg-primary p-3 m-2">{{reply.user}}<br/>{{ reply.body }}</p>
            {% endfor %}
            {% endwith %}
        </div><br/>

    {% empty %}
        <p>No Comment</p>
    {% endfor%}
{% endblock %}

A/home/templates/home/index.html
{% extends 'base.html' %}


{% block content%}
<div class="card">
    <h3>{{ request.user.username }}</h3>
    <form action="" method="get">
        {{form.as_p}}
        <input type="Submit" value="Search">
    </form>
    <br/><br/>
    {% for post in posts%}
        <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatewords:3 }}</a>
    {%endfor%}
</div>
{%endblock%}

A/home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}